language: nix

sudo: true

git:
  depth: 1

env:
  global:
  matrix:
    - GHCVERSION=ghc822
    - GHCVERSION=ghc844
    - GHCVERSION=ghc863

matrix:
  allow_failures:
  exclude:

script:
  - nix-build --argstr compiler $GHCVERSION

branches:
  only:
    - master
